-- =============================================================================
-- Manual Migration: Partial Unique Index for Sessions
-- =============================================================================
-- Purpose:
--   Enforce database-level uniqueness on active (non-cancelled) sessions.
--   A cancelled session (session_cancelled = 1/true) is excluded from the
--   constraint, allowing a rescheduled session to reuse the same
--   (round_id, session_type) combination with attempt_number incremented.
--
-- Why this is a manual migration (not generated by Prisma):
--   Prisma does not support partial unique indexes natively.
--   This SQL must be applied manually after `prisma migrate dev` creates the
--   sessions table. It is idempotent (IF NOT EXISTS guard).
--
-- Application-layer responsibility:
--   The ingestion pipeline determines attempt_number by querying
--   MAX(attempt_number) WHERE round_id = ? AND session_type = ?
--   before writing a new session record. This index is the second line of
--   defense — it rejects any duplicate that slips through (e.g. race condition
--   or pipeline bug).
--
-- How to apply:
--   After running `npx prisma migrate dev`, execute:
--     sqlite3 ./prisma/dev.db < ./prisma/migrations/manual/001_session_partial_unique.sql
--   For PostgreSQL (production):
--     psql $DATABASE_URL -f ./prisma/migrations/manual/001_session_partial_unique.sql
-- =============================================================================

-- SQLite version (development)
-- SQLite uses integer 0 for false booleans.
CREATE UNIQUE INDEX IF NOT EXISTS idx_session_active_unique
  ON sessions (round_id, session_type, attempt_number)
  WHERE session_cancelled = 0;

-- =============================================================================
-- PostgreSQL equivalent (production)
-- Comment out the SQLite version above and use this for production migrations.
-- PostgreSQL uses boolean FALSE natively.
-- =============================================================================
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_session_active_unique
--   ON sessions (round_id, session_type, attempt_number)
--   WHERE session_cancelled = FALSE;

-- =============================================================================
-- Verification query (run after applying to confirm the index exists):
--
-- SQLite:
--   SELECT name, sql FROM sqlite_master
--   WHERE type = 'index' AND name = 'idx_session_active_unique';
--
-- PostgreSQL:
--   SELECT indexname, indexdef FROM pg_indexes
--   WHERE indexname = 'idx_session_active_unique';
-- =============================================================================
