-- =============================================================================
-- Manual Migration: Partial Unique Index for car_circuit_performance
-- =============================================================================
-- Purpose:
--   Enforce database-level uniqueness on active (non-superseded) records.
--   A superseded record (superseded_at IS NOT NULL) is excluded from the
--   constraint, allowing amendment records to coexist with their predecessors
--   under the same (car_id, circuit_id, round_id, session_type) key.
--
-- Why this is a manual migration (not generated by Prisma):
--   The CarCircuitPerformance model has no @@unique in the Prisma schema
--   because that would block the amendment pattern entirely. Prisma does not
--   support partial unique indexes natively. This index is the sole database-
--   level uniqueness guard for active car_circuit_performance records.
--
--   IMPORTANT: Prisma's generated client has no awareness of this constraint.
--   Ingestion code must not assume @@unique upsert semantics on this model.
--   Application layer must check for existing active records before inserting.
--
-- How to apply:
--   After running `npx prisma migrate dev`, execute:
--     sqlite3 ./prisma/dev.db < ./prisma/migrations/manual/002_car_circuit_performance_partial_unique.sql
--   For PostgreSQL (production):
--     psql $DATABASE_URL -f ./prisma/migrations/manual/002_car_circuit_performance_partial_unique.sql
-- =============================================================================

-- SQLite version (development)
-- superseded_at IS NULL selects only active (non-amended) records.
CREATE UNIQUE INDEX IF NOT EXISTS idx_ccp_active_unique
  ON car_circuit_performance (car_id, circuit_id, round_id, session_type)
  WHERE superseded_at IS NULL;

-- =============================================================================
-- PostgreSQL equivalent (production — identical syntax)
-- =============================================================================
-- CREATE UNIQUE INDEX IF NOT EXISTS idx_ccp_active_unique
--   ON car_circuit_performance (car_id, circuit_id, round_id, session_type)
--   WHERE superseded_at IS NULL;

-- =============================================================================
-- Verification query:
-- SQLite:
--   SELECT name, sql FROM sqlite_master
--   WHERE type = 'index' AND name = 'idx_ccp_active_unique';
-- PostgreSQL:
--   SELECT indexname, indexdef FROM pg_indexes
--   WHERE indexname = 'idx_ccp_active_unique';
-- =============================================================================
